# Generated by Django 3.0.2 on 2020-02-27 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThirsdayTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incline_press', models.IntegerField(max_length=2)),
                ('dumbell_ohp', models.IntegerField(max_length=2)),
                ('chin_up', models.IntegerField(max_length=2)),
                ('barbell_row', models.IntegerField(max_length=2)),
                ('lying_dumbell_extension', models.IntegerField(max_length=2)),
                ('incline_dumbell_curl', models.IntegerField(blank=True, max_length=2, null=True)),
                ('hammer_curl', models.IntegerField(blank=True, max_length=2, null=True)),
                ('lateral_raise', models.IntegerField(max_length=2)),
                ('facepull', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(max_length=2)),
                ('finished', models.BooleanField(default=False)),
                ('average_weight', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WednesdayTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squat', models.IntegerField(max_length=3)),
                ('stiff_legged_deadlift', models.IntegerField(max_length=3)),
                ('lunges', models.IntegerField(max_length=2)),
                ('calf_raises', models.IntegerField(max_length=2)),
                ('hollow_body', models.IntegerField(blank=True, max_length=3, null=True)),
                ('weighted_crunches', models.IntegerField(blank=True, max_length=2, null=True)),
                ('cable_crunch', models.IntegerField(blank=True, max_length=2, null=True)),
                ('woodchoppers', models.IntegerField(blank=True, max_length=2, null=True)),
                ('russian_twist', models.IntegerField(blank=True, max_length=2, null=True)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyapp.Week')),
            ],
        ),
        migrations.CreateModel(
            name='MondayTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadlift', models.IntegerField(max_length=3)),
                ('pull_up', models.IntegerField(max_length=2)),
                ('dumbell_row', models.IntegerField(max_length=2)),
                ('barbell_curl', models.IntegerField(max_length=2)),
                ('facepull', models.IntegerField(max_length=2)),
                ('hollow_body', models.IntegerField(blank=True, max_length=3, null=True)),
                ('weighted_crunches', models.IntegerField(blank=True, max_length=2, null=True)),
                ('cable_crunch', models.IntegerField(blank=True, max_length=2, null=True)),
                ('woodchoppers', models.IntegerField(blank=True, max_length=2, null=True)),
                ('russian_twist', models.IntegerField(blank=True, max_length=2, null=True)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyapp.Week')),
            ],
        ),
        migrations.CreateModel(
            name='FridayTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_press', models.IntegerField(max_length=3)),
                ('barbell_ohp', models.IntegerField(max_length=2)),
                ('dips', models.IntegerField(max_length=2)),
                ('chest_fly', models.IntegerField(max_length=2)),
                ('lateral_raise', models.IntegerField(max_length=2)),
                ('triceps_pressdown', models.IntegerField(max_length=2)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyapp.Week')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=3)),
                ('finished', models.BooleanField(default=False)),
                ('count', models.IntegerField(max_length=1)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyapp.Week')),
            ],
        ),
    ]
