# Generated by Django 3.0.2 on 2020-02-28 11:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dailyapp', '0003_day_training_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='finished',
        ),
        migrations.AddField(
            model_name='day',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 28, 11, 38, 12, 337548, tzinfo=utc)),
        ),
    ]
