# Generated by Django 3.0.2 on 2020-02-29 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyapp', '0005_auto_20200228_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='SundayTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_press', models.IntegerField()),
                ('barbell_ohp', models.IntegerField()),
                ('dips', models.IntegerField()),
                ('chest_fly', models.IntegerField()),
                ('lateral_raise', models.IntegerField()),
                ('triceps_pressdown', models.IntegerField()),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dailyapp.Day')),
            ],
        ),
        migrations.RemoveField(
            model_name='mondaytraining',
            name='week',
        ),
        migrations.RemoveField(
            model_name='wednesdaytraining',
            name='week',
        ),
        migrations.AddField(
            model_name='mondaytraining',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dailyapp.Day'),
        ),
        migrations.AddField(
            model_name='thirsdaytraining',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dailyapp.Day'),
        ),
        migrations.AddField(
            model_name='wednesdaytraining',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dailyapp.Day'),
        ),
        migrations.DeleteModel(
            name='FridayTraining',
        ),
    ]
