# Generated by Django 3.0.2 on 2020-02-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyapp', '0006_auto_20200229_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mondaytraining',
            name='barbell_curl',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='mondaytraining',
            name='deadlift',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='mondaytraining',
            name='dumbell_row',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='mondaytraining',
            name='facepull',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='mondaytraining',
            name='pull_up',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sundaytraining',
            name='barbell_ohp',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sundaytraining',
            name='bench_press',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sundaytraining',
            name='chest_fly',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sundaytraining',
            name='dips',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sundaytraining',
            name='lateral_raise',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sundaytraining',
            name='triceps_pressdown',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='thirsdaytraining',
            name='barbell_row',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='thirsdaytraining',
            name='chin_up',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='thirsdaytraining',
            name='dumbell_ohp',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='thirsdaytraining',
            name='facepull',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='thirsdaytraining',
            name='hammer_curl',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thirsdaytraining',
            name='incline_dumbell_curl',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thirsdaytraining',
            name='incline_press',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='thirsdaytraining',
            name='lateral_raise',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='thirsdaytraining',
            name='lying_dumbell_extension',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='wednesdaytraining',
            name='cable_crunch',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wednesdaytraining',
            name='calf_raises',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='wednesdaytraining',
            name='hollow_body',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wednesdaytraining',
            name='lunges',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='wednesdaytraining',
            name='russian_twist',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wednesdaytraining',
            name='squat',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='wednesdaytraining',
            name='weighted_crunches',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wednesdaytraining',
            name='woodchoppers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
