# Generated by Django 3.0.2 on 2020-02-29 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyapp', '0008_auto_20200229_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='training_day',
        ),
    ]
