# Generated by Django 3.0.2 on 2020-03-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyapp', '0010_auto_20200301_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
