# Generated by Django 3.0.2 on 2020-03-01 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyapp', '0012_week_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mondaytraining',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sundaytraining',
            name='id',
        ),
        migrations.RemoveField(
            model_name='thirsdaytraining',
            name='id',
        ),
        migrations.RemoveField(
            model_name='wednesdaytraining',
            name='id',
        ),
        migrations.AlterField(
            model_name='mondaytraining',
            name='day',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dailyapp.Day'),
        ),
        migrations.AlterField(
            model_name='sundaytraining',
            name='day',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dailyapp.Day'),
        ),
        migrations.AlterField(
            model_name='thirsdaytraining',
            name='day',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dailyapp.Day'),
        ),
        migrations.AlterField(
            model_name='wednesdaytraining',
            name='day',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dailyapp.Day'),
        ),
    ]
