# Generated by Django 3.0.2 on 2020-03-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyapp', '0013_auto_20200301_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week',
            old_name='finished',
            new_name='is_finished',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='valid',
            new_name='is_valid',
        ),
    ]
