# Generated by Django 3.0.2 on 2020-03-04 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyapp', '0015_auto_20200304_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='day',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dailyapp.Day'),
        ),
    ]
