# Generated by Django 3.0.2 on 2020-03-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyapp', '0017_auto_20200304_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='bench_press',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
