# Generated by Django 3.0.2 on 2020-03-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyapp', '0018_auto_20200304_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='barbell_curl',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='barbell_ohp',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='barbell_row',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='calf_raises',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='chest_fly',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='chin_up',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='deadlift',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='dips',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='dumbell_ohp',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='dumbell_row',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='facepull',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='hammer_curl',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='incline_dumbell_curl',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='incline_press',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='lateral_raise',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='lunges',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='lying_dumbell_extension',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='pull_up',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='squat',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='stiff_legged_deadlift',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='triceps_pressdown',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
