# Generated by Django 3.0.2 on 2020-03-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyapp', '0019_auto_20200304_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='hammer_curl',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='incline_dumbell_curl',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
