# Generated by Django 3.0.2 on 2020-03-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyapp', '0020_auto_20200304_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
