# Generated by Django 3.0.2 on 2020-03-04 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyapp', '0021_training_is_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ('count',)},
        ),
    ]
