# Generated by Django 3.0.2 on 2020-03-06 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dailyapp', '0023_auto_20200305_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
