# Generated by Django 3.0.2 on 2020-03-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyapp', '0024_week_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='comment',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
