# Generated by Django 3.0.2 on 2020-03-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyapp', '0029_auto_20200323_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='average_weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
