# Generated by Django 3.0.2 on 2020-03-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyapp', '0041_auto_20200323_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='barbell_curl',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='barbell_ohp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='barbell_row',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='bench_press',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='cable_crunch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='calf_raises',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='chest_fly',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='chin_up',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='deadlift',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='dips',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='dumbell_ohp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='dumbell_row',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='facepull',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='hammer_curl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='hollow_body',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='incline_dumbell_curl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='incline_press',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='lateral_raise',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='lunges',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='lying_dumbell_extension',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='pull_up',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='russian_twist',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='squat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='stiff_legged_deadlift',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='triceps_pressdown',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='weighted_crunches',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='woodchoppers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
